### ISSUE TITLE
 the trait `core::cmp::Ord` is not implemented for the type `histogram::HistogramBucket`

### ISSUE THREAD

**Issue by posix4e** [brayniac/histogram#1]
Could this be based on the id?

**Comment by brayniac** [comment]
I'm curious about use-case for this. Should be a trivial change. But is a
bucket less than another if its id is lower (and thus the value)? Or if the
count is lower?

I need to give this some more thought. Having a clear use-case to consider
will help. Is there any reason not to compare the buckets by id or count
directly depending on intent?

**Comment by posix4e** [comment]
Actually this would be for calculating min,max,stddev,etc

**Comment by brayniac** [comment]
There's no total ordering of buckets that makes sense as a default. I'm unwilling to implement an order when the semantics are unclear.

**Comment by posix4e** [comment]
Sounds good thanks for you attention!
