### ISSUE TITLE
Metrics based histogram

### ISSUE THREAD

**Issue by posix4e** [brayniac/histogram#36]
I just got the request for a non-uniform histogram

https://github.com/posix4e/rust-metrics/issues/81

I assume people responding to the HDRhistogram stuff. What do we think?

**Comment by brayniac** [comment]
Hi @posix4e - I'm not sure specifically what about HDRHistogram you're referring to, could you elaborate here?

My impression for metrics use-cases: histograms are typically used in a latched fashion, eg: record for 60s, extract data, clear histogram, record for 60s.... This is how I implemented the metrics in https://github.com/brayniac/tic
