### ISSUE TITLE
"Value too small" when incrementing counter for 0

### ISSUE THREAD

**Issue by holtgrewe** [brayniac/histogram#48]
I wonder why 0 is too small a value in the implementation?

**Comment by brayniac** [comment]
Thanks for opening this. I was actually just questioning that yesterday while discussing this library with somebody else. It doesn't look like there's a reason to disallow for storing of counts for value of zero. I should have a PR following shortly to address this.

**Comment by holtgrewe** [comment]
Would it be possible to release a crate with this patch applied?
